spring:
  application:
    name: employee-app
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: root
    url: "jdbc:h2:mem:employees;DB_CLOSE_ON_EXIT=FALSE"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
